# Generated by Django 5.2.17 on 2026-08-04 18:02

import core.validators.phone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("donation_date", models.DateField()),
                ("donor_name", models.CharField(max_length=150)),
                (
                    "donor_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        validators=[core.validators.phone.validate_phone_number],
                    ),
                ),
                ("donor_address", models.TextField(blank=True, default="")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_mode",
                    models.CharField(choices=[("CASH", "Cash"), ("UPI", "UPI")], max_length=10),
                ),
                ("utr_number", models.CharField(blank=True, default="", max_length=64)),
                ("remarks", models.TextField(blank=True, default="")),
                (
                    "receipt_language",
                    models.CharField(
                        choices=[("EN", "English"), ("KN", "Kannada"), ("MR", "Marathi")],
                        default="EN",
                        max_length=5,
                    ),
                ),
                ("receipt_number", models.CharField(editable=False, max_length=32, unique=True)),
            ],
            options={
                "db_table": "donations",
                "ordering": ["-donation_date", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DonationCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "goal_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("color", models.CharField(blank=True, default="#6750A4", max_length=7)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Donation categories",
                "db_table": "donation_categories",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
    ]
