# Generated by Django 5.2.17 on 2026-08-04 18:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReceiptTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("EN", "English"), ("KN", "Kannada"), ("MR", "Marathi")],
                        max_length=5,
                        unique=True,
                    ),
                ),
                ("header_text", models.TextField(blank=True, default="")),
                ("footer_text", models.TextField(blank=True, default="")),
                ("show_signature_line", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "receipt_templates",
                "ordering": ["language"],
                "abstract": False,
            },
        ),
    ]
