# Generated by Django 5.2.17 on 2026-08-04 18:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("target_type", models.CharField(blank=True, default="", max_length=100)),
                ("target_id", models.CharField(blank=True, default="", max_length=64)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TempleSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("temple_name", models.CharField(default="", max_length=255)),
                ("address", models.TextField(blank=True, default="")),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("logo_url", models.URLField(blank=True, default="")),
                ("signature_url", models.URLField(blank=True, default="")),
                ("registration_number", models.CharField(blank=True, default="", max_length=100)),
                ("currency_symbol", models.CharField(default="₹", max_length=5)),
                ("receipt_prefix", models.CharField(default="TDMS", max_length=20)),
                ("last_receipt_number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Temple Settings",
                "verbose_name_plural": "Temple Settings",
                "db_table": "temple_settings",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
