# Generated by Django 5.2.17 on 2026-08-04 18:03

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="details",
            field=models.JSONField(
                blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
