# Generated by Django 5.2.16 on 2026-07-18 19:12

import core.validators.phone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[core.validators.phone.validate_phone_number]),
        ),
    ]
